---

- name: Fail if required Gitea settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - gitea_hostname
    - gitea_uid
    - gitea_gid
    - gitea_config_database_hostname
    - gitea_config_database_username
    - gitea_config_database_password

- when: gitea_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Gitea Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - gitea_container_labels_traefik_hostname
        - gitea_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `gitea_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if gitea_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          gitea_container_labels_traefik_path_prefix (`{{ gitea_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/gitea`).
      when: "gitea_container_labels_traefik_path_prefix != '/' and gitea_container_labels_traefik_path_prefix[-1] == '/'"
